[package]
name = "bins"
version = "0.1.0"
edition = "2021"
default-run = "raycast"

[dependencies]
macroquad = "0.3.20"

[dependencies.raycast]
package = "raycast"
path = "../src/raycast"

[[bin]]
name = "raycast"
path = "raycast.rs"

